# Generated by Django 5.1.11 on 2026-07-17 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("organization_verified", "Organization Verified"),
                            ("organization_unverified", "Organization Unverified"),
                            ("organization_activated", "Organization Activated"),
                            ("organization_deactivated", "Organization Deactivated"),
                            ("user_blocked", "User Blocked"),
                            ("user_unblocked", "User Unblocked"),
                            ("user_promoted", "User Promoted to Superadmin"),
                            ("user_demoted", "User Demoted from Superadmin"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.PositiveIntegerField()),
                ("target_repr", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "platform audit log",
                "ordering": ["-created_at"],
            },
        ),
    ]
