# Generated by Django 5.1.11 on 2026-10-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0002_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="topic",
            field=models.CharField(
                choices=[
                    ("general", "General question"),
                    ("organization", "Bring my organization to Gunaso"),
                    ("support", "Help with a submission"),
                    ("press", "Press & partnerships"),
                    ("child_safety", "Child safety concern"),
                    ("other", "Something else"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
