# Generated by Django 5.1.11 on 2026-07-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["name"], "verbose_name_plural": "organizations"},
        ),
        migrations.AlterModelOptions(
            name="stakeholder",
            options={
                "ordering": ["organization", "user"],
                "verbose_name_plural": "stakeholders",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
