# Generated by Django 5.1.11 on 2026-07-19 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_insights", "0001_initial"),
        ("organizations", "0007_branch"),
        ("submissions", "0005_submission_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("submission_count", models.PositiveIntegerField()),
                ("summary_nepali", models.TextField()),
                ("summary_english", models.TextField()),
                ("themes", models.JSONField(default=list)),
                ("sentiment_overview", models.TextField(blank=True)),
                ("recommendations", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_reports",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AISuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggestion_nepali", models.TextField()),
                ("suggestion_english", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestion",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI suggestion",
                "ordering": ["-updated_at"],
            },
        ),
    ]
