# Generated by Django 5.1.11 on 2026-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_email_verified_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_completed_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
