# Generated by Django 5.1.11 on 2026-07-02 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0002_alter_organization_options_alter_stakeholder_options_and_more",
        ),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statusupdate",
            options={
                "ordering": ["created_at"],
                "verbose_name_plural": "status updates",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-created_at"], "verbose_name_plural": "submissions"},
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="attachments/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="citizen_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="submission",
            name="citizen_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="submission",
            name="reference_number",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("acknowledged", "Acknowledged"),
                    ("in_review", "In Review"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                    ("escalated", "Escalated"),
                    ("closed", "Closed"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["organization", "status"], name="submissions_organiz_43c38c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["citizen", "-created_at"], name="submissions_citizen_94b4a4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "organization"), name="unique_category_per_org"
            ),
        ),
    ]
