# Generated by Django 5.1.11 on 2026-07-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organizationstaff"),
        (
            "submissions",
            "0002_alter_statusupdate_options_alter_submission_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_submissions",
                to="organizations.organizationstaff",
            ),
        ),
    ]
