# Generated by Django 5.1.11 on 2026-07-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_submission_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
