# Generated by Django 5.1.11 on 2026-07-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_branch"),
        ("submissions", "0004_submission_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="organizations.branch",
            ),
        ),
    ]
