# Generated by Django 5.1.11 on 2026-09-30 02:11

import django.core.validators
from django.db import migrations, models


def classify_existing_updates(apps, schema_editor):
    """Before `kind` existed, a staff note was a StatusUpdate whose status
    didn't change. The dashboard composer that wrote them was labelled
    "Internal note (not visible to citizen)" — yet they were served on the
    public track page. Backfill them as internal notes, honouring what the
    staff who wrote them were promised."""
    StatusUpdate = apps.get_model('submissions', 'StatusUpdate')
    StatusUpdate.objects.filter(old_status=models.F('new_status')).update(kind='internal_note')


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='kind',
            field=models.CharField(choices=[('status_change', 'Status change'), ('note', 'Staff reply'), ('internal_note', 'Internal note'), ('citizen_reply', 'Citizen follow-up')], default='status_change', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='followup_key_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='satisfaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='satisfaction_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='satisfaction_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RunPython(classify_existing_updates, migrations.RunPython.noop),
    ]
